url: ""
baseurl: ""
title: "Medusa Shopfront on Jekyll"

collections:
  pages:
    output: true

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js

jekyll-medusa:
  medusaApiUrl: "http://localhost:9000"
  medusaEndpoints:
    store:
      get: ["products", "collections"] # 'variants', 'regions', 'shipping-options'
