url: ""
baseurl: ""
title: "Medusa Shopfront on Jekyll"

collections:
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "default"
  -
    scope:
      type: products
    values:
      layout: product
      permalink: products/:product/

plugins:
  - jekyll-postcss
  - jekyll-datapage-generator # https://github.com/avillafiorita/jekyll-datapage_gen

page_gen-dirs: true

page_gen:
  - data: 'generated.products.products'
    template: 'product'
    name: 'handle'
    dir: 'products'

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js

jekyll-medusa:
  medusaApiUrl: "http://localhost:9000"
  medusaEndpoints:
    store:
      get: ["products", "collections"] # 'variants', 'regions', 'shipping-options'
