url: ''
baseurl: ''
title: 'Jekyllwind'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

jekyll-medusa:
  medusaApiUrl: 'http://localhost:9000'
